"""Exact interface for the ``{8,12}`` pairing theorem and its corollaries.

Blok's report *Sylver Coinage positions with g=2* (2021) states that the
simple pairing strategy suffices for the P-position ``{8,12}``.  This module
makes that theorem proof-grade for this repository and records the corollary
that both surveys overlooked: the even reply ``8`` resolves the holdout
``{12,16,20}``, because ``<12,16,20,8> = <8,12>`` exactly.

Theorem (``{8,12}`` is a P-position).  The gaps of ``B = <8,12>`` are ``1``,
``4``, every odd number, and every number ``2 (mod 4)``.  Pair them as

```text
special:  2 <-> 3,   4 <-> 6,
odd:      4j+1 <-> 4j+3,   j >= 1,
even:     8j+2 <-> 8j+6,   j >= 1,
```

with ``1`` unpaired.  The second player answers every move by its mate.
Write a *configuration* for the monoid ``T_C`` generated by ``B`` and the
members of a finite set ``C`` of completed pairs.  Three lemmas close the
strategy; the first two are quantified over every finite ``C`` and carry the
unbounded content, which the executable checks audit on long prefixes.

1. Gap-structure lemma.  ``gaps(T_C) = {1}`` union whole pairs.  With
   ``a = min odd index in C`` (``a = infinity`` if none), ``alpha`` marking
   whether pair ``a+1`` is also in ``C``, ``b = min even index``, and
   ``sigma1``/``sigma2`` marking the special pairs, the exact case analysis
   is: ``sigma1`` gives gaps ``{1}``; otherwise the odd gaps are all odd
   numbers below ``4a+1``, together with ``{4a+5,4a+7}`` when neither
   ``sigma2`` nor ``alpha`` holds; the ``2 (mod 4)`` gaps are ``{2}`` for
   ``sigma2`` and otherwise ``{2,6}`` together with ``{8j+2,8j+6}`` for
   ``j < min(a,b)``; and ``4`` is a gap exactly when ``sigma2`` fails.
   Every displayed set is a union of whole pairs.  The proof is composition
   arithmetic: completing an odd pair ``o_a`` adds ``2(4a+1)=8a+2`` and
   ``2(4a+3)=8a+6``, so even pairs at indices ``>= a`` die whole, while
   ``4a+5`` and ``4a+7`` need ``4`` or the next odd pair; completing ``e_b``
   adds nothing odd; the special pair ``{2,3}`` generates every integer
   beyond ``1``; and ``{4,6}`` absorbs every even pair.

2. Mate-survival lemma.  If ``{x,y}`` is a whole pair of ``gaps(T_C)`` and
   the opponent plays ``x``, then ``y`` is still legal.  Otherwise
   ``y = t + k*x`` with ``t`` in ``T_C``; ``k = 0`` contradicts ``y`` being
   a gap; ``k >= 2`` makes ``t`` negative since every pair satisfies
   ``2x > y``; and ``k = 1`` forces ``t = |y-x|`` in ``{1,2,4}``.  ``1`` is
   never in ``T_C``; ``2`` requires ``sigma1``, which leaves no pair; ``4``
   requires ``sigma2``, which kills every pair at difference four.

3. Termination.  Completing ``{2,3}`` leaves gaps ``{1}``; completions of
   even pairs strictly decrease ``min(a,b)``; the first completed odd or
   special pair leaves finitely many gaps.  Hence every play is finite, the
   second player always holds a reply other than ``1``, and the opponent
   eventually names ``1``.  Therefore ``{8,12}`` is a P-position.

Corollary.  ``8`` is a gap of ``<12,16,20>`` and ``16 = 8+8``,
``20 = 8+12`` give ``<12,16,20,8> = <8,12>`` exactly, so ``{12,16,20}`` is
an N-position with the even winning reply ``8``.  Both Blok's 2021
conclusion ("the completion requires knowing a good, odd reply to
{12,16,20}, which so far, I do not know") and this repository's bounded odd
frontier through 409 searched the odd side of a position that the even
reply settles.  The same identity ``28 = 12+16`` reduces the gcd-four
candidate branch ``{16,20,28} + 12`` to ``{12,16,20}``, so that branch is
refuted by the same reply.
"""

from __future__ import annotations

from dataclasses import dataclass

from sylver.short_certificates import is_generated, minimal_generators

BASE = (8, 12)


def eight_twelve_pair(move: int) -> int | None:
    """Return the mate of a legal ``{8,12}`` move, or ``None`` for ``1``.

    Raises ``ValueError`` when ``move`` is not a gap of ``<8,12>``.
    """

    if not isinstance(move, int) or isinstance(move, bool) or move < 1:
        raise ValueError("move must be a positive integer")
    if move % 4 == 0 and move != 4:
        raise ValueError("move is not legal in {8,12}")
    if move == 1:
        return None
    if move in (2, 3):
        return 5 - move
    if move in (4, 6):
        return 10 - move
    if move % 2:
        return move + 2 if move % 4 == 1 else move - 2
    return move + 4 if move % 8 == 2 else move - 4


def configuration_generators(
    special_one: bool,
    special_two: bool,
    odd_indices: tuple[int, ...],
    even_indices: tuple[int, ...],
) -> tuple[int, ...]:
    """Return the generators of one completed-pair configuration."""

    if any(index < 1 for index in (*odd_indices, *even_indices)):
        raise ValueError("pair indices must be positive integers")
    generators = set(BASE)
    if special_one:
        generators.update((2, 3))
    if special_two:
        generators.update((4, 6))
    for index in odd_indices:
        generators.update((4 * index + 1, 4 * index + 3))
    for index in even_indices:
        generators.update((8 * index + 2, 8 * index + 6))
    return tuple(sorted(generators))


@dataclass(frozen=True)
class ConfigurationCertificate:
    """Exact audit of one configuration against both lemmas.

    ``class_minima`` maps each residue modulo eight to the least monoid
    element in that class, or ``None`` for a provably empty class.  Because
    ``8`` is a generator, each class is upward closed, so the minima
    describe the monoid completely and the gap set exactly, including its
    infinite residue classes.
    """

    generators: tuple[int, ...]
    class_minima: tuple[int | None, ...]
    window_gaps: tuple[int, ...]
    whole_pairs: tuple[tuple[int, int], ...]
    infinite_classes: tuple[int, ...]


def configuration_certificate(
    special_one: bool,
    special_two: bool,
    odd_indices: tuple[int, ...],
    even_indices: tuple[int, ...],
) -> ConfigurationCertificate:
    """Verify the gap-structure and mate-survival lemmas exactly.

    A residue class modulo eight is nonempty exactly when it lies in the
    submonoid of ``Z/8`` generated by the generator residues; any nonempty
    class attains its minimum within seven generator additions.  Both facts
    make the class-minima table below exact rather than a cutoff.  The gap
    set is then ``{x = r (mod 8) : x < m_r}`` over all classes, with empty
    classes contributing an infinite all-gap tail.  The certificate checks:

    - every finite gap other than ``1`` has its mate as a gap;
    - the infinite classes couple exactly under the mate maps
      (``1`` with ``3``, ``5`` with ``7``, ``2`` with ``6``);
    - playing either member of a whole pair in the window leaves the other
      member legal (mate survival).
    """

    generators = configuration_generators(
        special_one, special_two, odd_indices, even_indices
    )
    bound = 8 * max(generators) + 64
    reachable = bytearray(bound + 1)
    reachable[0] = 1
    for current in range(bound + 1):
        if not reachable[current]:
            continue
        for generator in generators:
            if current + generator <= bound:
                reachable[current + generator] = 1

    residue_monoid = {0}
    while True:
        extended = residue_monoid | {
            (residue + generator) % 8
            for residue in residue_monoid
            for generator in generators
        }
        if extended == residue_monoid:
            break
        residue_monoid = extended

    minima: list[int | None] = []
    for residue in range(8):
        found = next(
            (
                value
                for value in range(residue, bound + 1, 8)
                if reachable[value] or (value == 0)
            ),
            None,
        )
        if (residue in residue_monoid) != (found is not None):
            raise AssertionError("residue-class emptiness proof failed")
        if found is not None and found > 7 * max(generators):
            raise AssertionError("class minimum exceeded its exact bound")
        minima.append(found)
    if minima[0] != 0 or minima[4] is None or minima[4] > 12:
        raise AssertionError("classes 0 and 4 must be trivial")

    infinite_classes = tuple(
        residue for residue in range(8) if minima[residue] is None
    )
    for left, right in ((1, 3), (5, 7), (2, 6)):
        if (minima[left] is None) != (minima[right] is None):
            raise AssertionError("infinite gap classes fail to couple")

    window = max(
        (value for value in minima if value is not None), default=0
    ) + 16
    window_gaps = tuple(
        value
        for value in range(1, window)
        if minima[value % 8] is None or value < minima[value % 8]
    )
    if not window_gaps or window_gaps[0] != 1:
        raise AssertionError("1 must remain the least gap")

    pairs: list[tuple[int, int]] = []
    seen: set[int] = set()
    for move in window_gaps:
        if move == 1 or move in seen:
            continue
        mate = eight_twelve_pair(move)
        if mate is None:
            raise AssertionError("only 1 may be unpaired")
        mate_is_gap = (
            minima[mate % 8] is None or mate < minima[mate % 8]
        )
        if not mate_is_gap:
            raise AssertionError(
                f"gap {move} lost its mate: gap-structure lemma failed"
            )
        seen.update((move, mate))
        pairs.append((min(move, mate), max(move, mate)))

    for low, high in pairs:
        for played, mate in ((low, high), (high, low)):
            if is_generated((*generators, played), mate):
                raise AssertionError(
                    f"mate {mate} became illegal after {played}"
                )

    return ConfigurationCertificate(
        generators=generators,
        class_minima=tuple(minima),
        window_gaps=window_gaps,
        whole_pairs=tuple(pairs),
        infinite_classes=infinite_classes,
    )


@dataclass(frozen=True)
class PairingAuditReport:
    """Summary of an exhaustive-plus-parametric configuration audit."""

    exhaustive_configurations: int
    parametric_configurations: int
    total_whole_pairs_checked: int


def verify_eight_twelve_pairing(
    exhaustive_bound: int = 4, parametric_bound: int = 40
) -> PairingAuditReport:
    """Audit both lemmas over a dense prefix of configurations.

    Every subset of odd pairs ``o_1..o_k`` and even pairs ``e_1..e_k`` with
    ``k = exhaustive_bound`` is checked under all four special-pair states,
    and sparse single/double completions are checked out to
    ``parametric_bound``.  The unbounded quantifier is carried by the case
    analysis in the module docstring, exactly as with Blok's finite-member
    checks of the ``{8,12,8n+2,8n+6}`` family.
    """

    exhaustive = 0
    parametric = 0
    pairs_checked = 0
    subsets = [
        tuple(
            index + 1
            for index in range(exhaustive_bound)
            if mask & (1 << index)
        )
        for mask in range(1 << exhaustive_bound)
    ]
    for special_one in (False, True):
        for special_two in (False, True):
            for odd_indices in subsets:
                for even_indices in subsets:
                    certificate = configuration_certificate(
                        special_one, special_two, odd_indices, even_indices
                    )
                    exhaustive += 1
                    pairs_checked += len(certificate.whole_pairs)
    for index in range(exhaustive_bound + 1, parametric_bound + 1):
        for odd_indices, even_indices in (
            ((index,), ()),
            ((), (index,)),
            ((index, index + 1), ()),
            ((index,), (index,)),
            ((index,), (max(1, index // 2),)),
        ):
            certificate = configuration_certificate(
                False, False, odd_indices, even_indices
            )
            parametric += 1
            pairs_checked += len(certificate.whole_pairs)
    return PairingAuditReport(
        exhaustive_configurations=exhaustive,
        parametric_configurations=parametric,
        total_whole_pairs_checked=pairs_checked,
    )


@dataclass(frozen=True)
class HoldoutResolution:
    """The even reply that settles ``{12,16,20}`` and the candidate branch."""

    holdout: tuple[int, ...]
    winning_reply: int
    reached_position: tuple[int, ...]
    candidate_branch: tuple[int, ...]


def holdout_even_reply_resolution() -> HoldoutResolution:
    """Verify exactly that ``8`` wins from ``{12,16,20}``.

    Checks, with no cutoff: ``8`` is a gap of ``<12,16,20>``; the monoid
    ``<12,16,20,8>`` has minimal generators ``(8,12)`` (both inclusions are
    the identities ``16=8+8`` and ``20=8+12``); and the gcd-four candidate
    branch ``<16,20,28,12>`` reduces to ``<12,16,20>`` via ``28=12+16``.
    The reached position is the pairing-theorem P-position ``{8,12}``.
    """

    holdout = (12, 16, 20)
    if minimal_generators(holdout) != holdout:
        raise AssertionError("holdout generators are not minimal")
    if is_generated(holdout, 8):
        raise AssertionError("8 must be a legal move from {12,16,20}")
    reached = minimal_generators((*holdout, 8))
    if reached != BASE:
        raise AssertionError("<12,16,20,8> must equal <8,12>")
    if 16 != 8 + 8 or 20 != 8 + 12 or 28 != 12 + 16:
        raise AssertionError("generator identities failed")
    candidate_branch = minimal_generators((16, 20, 28, 12))
    if candidate_branch != holdout:
        raise AssertionError("<16,20,28,12> must equal <12,16,20>")
    return HoldoutResolution(
        holdout=holdout,
        winning_reply=8,
        reached_position=reached,
        candidate_branch=candidate_branch,
    )
