#!/usr/bin/env python3
"""Solve finite (gcd-one) positions in Conway's Sylver Coinage.

A position is the numerical semigroup generated by all moves so far.  Once the
generators have gcd one, its legal moves are the finite set of gaps of that
semigroup.  This module evaluates that finite impartial game exactly.  It does
not claim to solve positions of gcd greater than one, including ``{16}``.
"""

from __future__ import annotations

import argparse
import functools
import heapq
import math
from collections.abc import Iterable, Sequence
from dataclasses import dataclass


def normalize_generators(generators: Iterable[int]) -> tuple[int, ...]:
    """Return sorted, distinct generators after validating them."""
    values = tuple(generators)
    if not values or any(
        isinstance(value, bool) or not isinstance(value, int) for value in values
    ):
        raise ValueError("generators must be integers")
    result = tuple(sorted(set(values)))
    if result[0] < 2:
        raise ValueError("generators must be distinct integers greater than 1")
    if math.gcd(*result) != 1:
        raise ValueError("exact evaluation requires generators with gcd 1")
    return result


def apery_set(generators: Sequence[int]) -> tuple[int, ...]:
    """Compute the Apéry set using shortest paths modulo the least generator."""
    modulus = min(generators)
    distance = [math.inf] * modulus
    distance[0] = 0
    queue: list[tuple[int, int]] = [(0, 0)]

    while queue:
        value, residue = heapq.heappop(queue)
        if value != distance[residue]:
            continue
        for generator in generators:
            candidate = value + generator
            next_residue = candidate % modulus
            if candidate < distance[next_residue]:
                distance[next_residue] = candidate
                heapq.heappush(queue, (candidate, next_residue))

    if any(value == math.inf for value in distance):  # Defensive; gcd=1 suffices.
        raise ValueError("generators do not define a numerical semigroup")
    return tuple(int(value) for value in distance)


def frobenius_number(generators: Sequence[int]) -> int:
    """Return the largest integer outside the generated numerical semigroup."""
    return max(apery_set(generators)) - min(generators)


@dataclass(frozen=True)
class HoldoutOddSemigroupReport:
    """Closed-form gap data for ``<12,16,20,m>`` with odd ``m``."""

    move: int
    frobenius: int
    genus: int
    gaps: tuple[int, ...]


def holdout_odd_semigroup_report(move: int) -> HoldoutOddSemigroupReport:
    """Return the complete gaps of ``<12,16,20,move>`` in closed form.

    The even subsemigroup is

    ``<12,16,20> = {0} union {4*t : t >= 3}``.

    Since ``move`` is odd, every coefficient of it reduces uniquely modulo
    four: four copies already belong to the even subsemigroup.  In the residue
    represented by ``k*move``, ``0 <= k < 4``, every positive value below
    ``k*move`` is therefore a gap; ``k*move`` is represented; the next two
    values ``k*move+4`` and ``k*move+8`` are gaps; and every later value is
    represented.  This partitions all four residue classes exactly.
    """

    if (
        not isinstance(move, int)
        or isinstance(move, bool)
        or move < 3
        or move % 2 == 0
    ):
        raise ValueError("move must be an odd integer at least three")
    gaps: list[int] = []
    for coefficient in range(4):
        anchor = coefficient * move
        residue = anchor % 4
        first_positive = residue or 4
        gaps.extend(range(first_positive, anchor, 4))
        gaps.extend((anchor + 4, anchor + 8))
    result = tuple(sorted(gaps))
    frobenius = 3 * move + 8
    genus = (3 * move + 13) // 2
    if result[-1] != frobenius or len(result) != genus:
        raise AssertionError("closed-form holdout gap count failed")
    return HoldoutOddSemigroupReport(move, frobenius, genus, result)


@dataclass(frozen=True)
class Solution:
    """Exact outcome of a finite position."""

    generators: tuple[int, ...]
    frobenius: int
    winning_move: int | None
    states_evaluated: int

    @property
    def is_winning(self) -> bool:
        return self.winning_move is not None


class FiniteSolver:
    """Memoized exact evaluator for one gcd-one starting position.

    Bit ``n`` in a state is one exactly when ``n`` is already in the numerical
    semigroup and hence is not a legal move.  Bit zero is included so that
    adding a generator can be implemented as shift-and-union closure.
    """

    def __init__(self, generators: Iterable[int]) -> None:
        self.generators = normalize_generators(generators)
        self.frobenius = frobenius_number(self.generators)
        self._mask = (1 << (self.frobenius + 1)) - 1
        self._playable_mask = self._mask & ~0b11  # Exclude 0 and losing move 1.
        state = 1  # Zero belongs to every numerical semigroup.
        for generator in self.generators:
            state = self._adjoin(state, generator)
        self.initial_state = state

    def _adjoin(self, state: int, move: int) -> int:
        """Close a represented set under addition of any multiple of ``move``."""
        shift = move
        result = state
        while shift <= self.frobenius:
            result |= (result << shift) & self._mask
            shift *= 2
        return result

    def legal_moves(self, state: int) -> tuple[int, ...]:
        """Return all non-losing legal moves in increasing order."""
        gaps = self._playable_mask & ~state
        moves: list[int] = []
        while gaps:
            least_bit = gaps & -gaps
            moves.append(least_bit.bit_length() - 1)
            gaps ^= least_bit
        return tuple(moves)

    def gaps(self, state: int | None = None) -> tuple[int, ...]:
        """Return all legal moves, including the poisoned move 1."""
        if state is None:
            state = self.initial_state
        return (1, *self.legal_moves(state))

    def is_quiet_ender(self, state: int | None = None) -> bool:
        """Test the antisymmetry characterization of a quiet ender."""
        if state is None:
            state = self.initial_state
        gaps = self.gaps(state)
        top = gaps[-1]
        gap_set = set(gaps)
        return all(
            (value in gap_set) != (top - value in gap_set)
            for value in range(top + 1)
        )

    def solve(self) -> Solution:
        """Evaluate the starting position and return one winning move, if any."""

        @functools.cache
        def winning_move(state: int) -> int:
            # If x followed by r reaches a P-position, commutativity lets x
            # refute a later trial of r.  Recording that pairing is exact and
            # avoids evaluating the same two-move state in both orders.
            paired_losers = 0
            for move in self.legal_moves(state):
                move_bit = 1 << move
                if paired_losers & move_bit:
                    continue
                child = self._adjoin(state, move)
                response = winning_move(child)
                if response == 0:
                    return move
                if response > move:
                    paired_losers |= 1 << response
            return 0

        move = winning_move(self.initial_state)
        return Solution(
            generators=self.generators,
            frobenius=self.frobenius,
            winning_move=move or None,
            states_evaluated=winning_move.cache_info().currsize,
        )


def solve_position(generators: Iterable[int]) -> Solution:
    """Convenience wrapper for exact evaluation of a gcd-one position."""
    return FiniteSolver(generators).solve()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="exactly evaluate a finite Sylver Coinage position"
    )
    parser.add_argument("generators", metavar="N", type=int, nargs="+")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        solution = solve_position(args.generators)
    except ValueError as error:
        raise SystemExit(str(error)) from error

    position = ", ".join(str(value) for value in solution.generators)
    outcome = (
        f"N; winning move {solution.winning_move}"
        if solution.is_winning
        else "P"
    )
    print(f"{{{position}}}: {outcome}")
    print(
        f"Frobenius number: {solution.frobenius}; "
        f"states evaluated: {solution.states_evaluated}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
