"""Sylver Coinage rules for arena play: capped moves and an exact end test.

Bit n of ``members`` is set exactly when n (0 <= n <= max_move) lies in the
semigroup generated by the named numbers. The player to move must name 1,
and so loses, exactly when 2 and 3 are members: if every integer in
[2, max_move] were a member, 2 and 3 would be, and 2a+3b covers every
integer above 1. A move cap therefore never ends a game early; it only
removes larger moves, and play is exact Sylver Coinage whenever the
position has gcd one and Frobenius number at most the cap.
"""
from functools import reduce
from math import gcd

from sylver.solver import frobenius_number

DEFAULT_MAX_MOVE = 1000
MAX_MOVE_LIMIT = 1 << 20


class IllegalMove(ValueError):
    """Not a legal move of at least 2 in this position."""


def _adjoin(bits, move, limit):
    mask = (1 << (limit + 1)) - 1
    shift = move
    while shift <= limit:
        bits |= (bits << shift) & mask
        shift *= 2
    return bits


def minimal_generators(values):
    values = sorted(set(values))
    result, bits = [], 1
    top = values[-1] if values else 0
    for v in values:
        if not bits >> v & 1:
            result.append(v)
            bits = _adjoin(bits, v, top)
    return tuple(result)


class Position:
    """Immutable: the start generators, the moves named since, and the cap."""
    __slots__ = ('max_move', 'start', 'history', 'members', 'generators')

    def __init__(self, start=(), history=(), max_move=DEFAULT_MAX_MOVE):
        start, history = tuple(start), tuple(history)       # iterators are read once
        if type(max_move) is not int or not 3 <= max_move <= MAX_MOVE_LIMIT:
            raise ValueError(f'max_move must be an integer in [3, {MAX_MOVE_LIMIT}]')
        if any(type(v) is not int or not 2 <= v <= max_move for v in start):
            raise ValueError('start generators must be integers in [2, max_move]')
        self.max_move = max_move
        self.start = minimal_generators(start)
        self.history = ()
        self.generators = self.start
        members = 1
        for v in self.start:
            members = _adjoin(members, v, max_move)
        self.members = members
        position = self
        for move in history:
            position = position.play(move)
        self.history, self.members, self.generators = position.history, position.members, position.generators

    def is_legal(self, n):
        return type(n) is int and 1 <= n <= self.max_move and not self.members >> n & 1

    def play(self, n):
        if n == 1 or not self.is_legal(n):
            raise IllegalMove(f'{n!r} is not a legal move of at least 2')
        child = object.__new__(Position)
        child.max_move, child.start = self.max_move, self.start
        child.history = self.history + (n,)
        child.members = _adjoin(self.members, n, self.max_move)
        child.generators = minimal_generators(self.generators + (n,))
        return child

    def over(self):
        return self.members & 0b1100 == 0b1100

    def gcd(self):
        return reduce(gcd, self.generators, 0)

    def frobenius(self):
        return frobenius_number(self.generators) if self.gcd() == 1 else None

    def capped(self):
        return self.gcd() != 1 or self.frobenius() > self.max_move

    def legal_moves(self):
        free = ~self.members & ((1 << (self.max_move + 1)) - 1) & ~0b11
        moves = []
        while free:
            low = free & -free
            moves.append(low.bit_length() - 1)
            free ^= low
        return moves

    def key(self):
        return ','.join(map(str, self.generators))
